name 'Ancillas/iis'
version '1.2.0'
author 'Ancillas'
license 'MIT'
summary 'Module that will manage IIS for windows server 2008 and above. It will help maintain application pools, sites and virtual applications'
project_page 'https://github.com/Ancillas/puppet-iis'
dependency    'puppetlabs/stdlib', '>=3.0.0'
dependency    'joshcooper/powershell', '>=0.0.6'
